// SPDX-License-Identifier: AGPL-3.0-or-later
//! build.rs — drives the CMake compilation of `libomni_wst_bridge.so` and
//! feeds the output linker flags to Cargo so it can link the Rust crate.
//!
//! Steps performed:
//!  1. Invoke CMake on the root `omni-wst-core` repo with `BUILD_CXX_BRIDGE=ON`.
//!  2. Pass the `cxx`-generated `rust/cxx.h` directory so the CUDA bridge code
//!     can find the cxx C++ header (`#include "rust/cxx.h"`).
//!  3. Emit `cargo:rustc-link-*` directives so the linker finds the .so.
//!  4. Use `cxx_build` to compile the bridge C++ glue generated by `#[cxx::bridge]`.

use std::{env, path::PathBuf};

fn main() {
    // -----------------------------------------------------------------------
    // 1. Locate the root of the omni-wst-core repo relative to this crate.
    //    Layout:  <repo>/crates/omni-wst-sys/build.rs
    //             <repo>/CMakeLists.txt
    // -----------------------------------------------------------------------
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()   // crates/
        .unwrap()
        .parent()   // <repo>/
        .unwrap()
        .to_path_buf();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let bridge_build_dir = out_dir.join("cmake_bridge");

    // -----------------------------------------------------------------------
    // 2. cxx-build compiles the #[cxx::bridge] generated glue.
    //    This also tells cxx to generate `rust/cxx.h` into OUT_DIR, which
    //    we then pass to CMake via OMNI_CXX_INCLUDE_DIR.
    // -----------------------------------------------------------------------
    let mut bridge = cxx_build::bridge("src/lib.rs");
    bridge
        .std("c++17")
        .include(&repo_root.join("cpp"))
        .compile("omni_wst_cxxglue");

    // The generated `rust/cxx.h` lives in OUT_DIR — CMake needs to know this
    let cxx_header_dir = out_dir.clone();

    // -----------------------------------------------------------------------
    // 3. Run CMake to build libomni_wst_bridge.so
    //    Requires CUDA toolkit and nvcc to be on PATH (guaranteed in CI).
    // -----------------------------------------------------------------------
    cmake::Config::new(&repo_root)
        .define("BUILD_CXX_BRIDGE", "ON")
        .define("OMNI_CXX_INCLUDE_DIR", cxx_header_dir.to_str().unwrap())
        .build_target("omni_wst_bridge")
        .build();

    // cmake::Config::build() returns the build output directory
    let cmake_lib_dir = bridge_build_dir.join("build");

    // -----------------------------------------------------------------------
    // 4. Emit linker directives
    // -----------------------------------------------------------------------
    // Tell Cargo where to find libomni_wst_bridge.so
    println!("cargo:rustc-link-search=native={}", cmake_lib_dir.display());
    println!("cargo:rustc-link-lib=dylib=omni_wst_bridge");

    // Link CUDA runtime (required at runtime when the .so calls cudaFree etc.)
    // The CUDA toolkit lib path is typically under /usr/local/cuda/lib64
    if let Ok(cuda_path) = env::var("CUDA_ROOT") {
        println!("cargo:rustc-link-search=native={}/lib64", cuda_path);
    } else {
        // Common default path on NVIDIA CUDA images
        println!("cargo:rustc-link-search=native=/usr/local/cuda/lib64");
    }
    println!("cargo:rustc-link-lib=dylib=cudart");

    // -----------------------------------------------------------------------
    // 5. Re-run if any C++ source changes
    // -----------------------------------------------------------------------
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=../../cpp/wst_bridge.h");
    println!("cargo:rerun-if-changed=../../cpp/wst_bridge.cu");
    println!("cargo:rerun-if-changed=../../cpp/wst_kernel.cuh");
    println!("cargo:rerun-if-changed=../../cpp/jtfs_kernel.cuh");
    println!("cargo:rerun-if-changed=../../CMakeLists.txt");
}
